name: build

on:
  - push

permissions: read-all

jobs:
  setup-prerequisites:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3.2.7
        with:
          ocaml-compiler: 5.1.1

      - run: opam install . --deps-only --with-test
      - run: opam exec -- dune build
  
